### ISSUE TITLE
using pre-release poetry

### ISSUE THREAD

**Issue by tok41** [tok41/basic-dev-env#7]
# 課題

２０２２年７月現在のpoetryの最新バージョンは1.1.13 ?なのだが、 `pytorch` のインストールでエラーが出る。

参考：[Poetry で PyTorch + Torchvision 再々チャレンジ作業ログ（成功）](https://scrapbox.io/ikr7/Poetry_%E3%81%A7_PyTorch_+_Torchvision_%E5%86%8D%E3%80%85%E3%83%81%E3%83%A3%E3%83%AC%E3%83%B3%E3%82%B8%E4%BD%9C%E6%A5%AD%E3%83%AD%E3%82%B0%EF%BC%88%E6%88%90%E5%8A%9F%EF%BC%89)

なので、pre-release版のpoetryをインストールしたい

以下参考

https://python-poetry.org/docs/master/#installing-with-the-official-installer

**Comment by tok41** [comment]
`Dockerfile` でpoetryのインストールコマンド以下のように変更したら、無事に `1.2.0a2` がインストールできたぽい

```
curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.2.0a2 python -
```

**Comment by tok41** [comment]
しかし、pytorchのインストールでエラーが出るな。。。

release版を使ってたときよりも進んでいるので、進展はあったぽい？

```shell
# poetry add pytorch
Using version ^1.0.2 for pytorch

Updating dependencies
Resolving dependencies... (91.3s)PackageInfo: Invalid constraint (tinycss2 (>=1.1.0<1.2) ; extra == 'css') found in bleach-5.0.0 dependencies, skipping
<debug>PackageInfo:</debug> Invalid constraint (tinycss2 (>=1.1.0<1.2) ; extra == 'css') found in bleach-5.0.0 dependencies, skipping
Resolving dependencies... (137.8s)PackageInfo: Invalid constraint (tinycss2 (>=1.1.0<1.2) ; extra == 'css') found in bleach-5.0.0 dependencies, skipping
<debug>PackageInfo:</debug> Invalid constraint (tinycss2 (>=1.1.0<1.2) ; extra == 'css') found in bleach-5.0.0 dependencies, skipping
Resolving dependencies... (140.3s)PackageInfo: Invalid constraint (tinycss2 (>=1.1.0<1.2) ; extra == 'css') found in bleach-5.0.0 dependencies, skipping
<debug>PackageInfo:</debug> Invalid constraint (tinycss2 (>=1.1.0<1.2) ; extra == 'css') found in bleach-5.0.0 dependencies, skipping
Resolving dependencies... (143.6s)PackageInfo: Invalid constraint (tinycss2 (>=1.1.0<1.2) ; extra == 'css') found in bleach-5.0.0 dependencies, skipping
<debug>PackageInfo:</debug> Invalid constraint (tinycss2 (>=1.1.0<1.2) ; extra == 'css') found in bleach-5.0.0 dependencies, skipping
Resolving dependencies... (144.4s)

Writing lock file

Package operations: 1 install, 1 update, 0 removals

  • Updating setuptools (60.6.0 -> 63.1.0)
  • Installing pytorch (1.0.2): Failed

  CalledProcessError

  Command '['/workspace/.venv/bin/python', '/opt/poetry/venv/lib/python3.10/site-packages/virtualenv/seed/wheels/embed/pip-21.0.1-py3-none-any.whl/pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/workspace/.venv', '--no-deps', '/root/.cache/pypoetry/artifacts/50/6f/ff/4ff20a62776b87b2ce071ac4039796d19cf95b3d467b9dfd00fa994b17/pytorch-1.0.2.tar.gz']' returned non-zero exit status 1.

  at /usr/local/lib/python3.10/subprocess.py:524 in run
       520│             # We don't call process.wait() as .__exit__ does that for us.
       521│             raise
       522│         retcode = process.poll()
       523│         if check and retcode:
    →  524│             raise CalledProcessError(retcode, process.args,
       525│                                      output=stdout, stderr=stderr)
       526│     return CompletedProcess(process.args, retcode, stdout, stderr)
       527│ 
       528│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/workspace/.venv/bin/python', '/opt/poetry/venv/lib/python3.10/site-packages/virtualenv/seed/wheels/embed/pip-21.0.1-py3-none-any.whl/pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/workspace/.venv', '--no-deps', '/root/.cache/pypoetry/artifacts/50/6f/ff/4ff20a62776b87b2ce071ac4039796d19cf95b3d467b9dfd00fa994b17/pytorch-1.0.2.tar.gz'] errored with the following return code 1, and output: 
  Processing /root/.cache/pypoetry/artifacts/50/6f/ff/4ff20a62776b87b2ce071ac4039796d19cf95b3d467b9dfd00fa994b17/pytorch-1.0.2.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Building wheels for collected packages: pytorch
    Building wheel for pytorch (PEP 517): started
    Building wheel for pytorch (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /workspace/.venv/bin/python /tmp/tmpz8ss3d3j_in_process.py build_wheel /tmp/tmpnx8qe3z3
         cwd: /tmp/pip-req-build-sh85j423
    Complete output (18 lines):
    Traceback (most recent call last):
      File "/tmp/tmpz8ss3d3j_in_process.py", line 280, in <module>
        main()
      File "/tmp/tmpz8ss3d3j_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmpz8ss3d3j_in_process.py", line 204, in build_wheel
        return _build_backend().build_wheel(wheel_directory, config_settings,
      File "/tmp/pip-build-env-o98bkyy8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 244, in build_wheel
        return self._build_with_temp_dir(['bdist_wheel'], '.whl',
      File "/tmp/pip-build-env-o98bkyy8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
        self.run_setup()
      File "/tmp/pip-build-env-o98bkyy8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 281, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/tmp/pip-build-env-o98bkyy8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 15, in <module>
        raise Exception(message)
    Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
    ----------------------------------------
    ERROR: Failed building wheel for pytorch
  Failed to build pytorch
  ERROR: Could not build wheels for pytorch which use PEP 517 and cannot be installed directly
  

  at /opt/poetry/venv/lib/python3.10/site-packages/poetry/utils/env.py:1300 in _run
      1296│                 output = subprocess.check_output(
      1297│                     cmd, stderr=subprocess.STDOUT, env=env, **kwargs
      1298│                 )
      1299│         except CalledProcessError as e:
    → 1300│             raise EnvCommandError(e, input=input_)
      1301│ 
      1302│         return decode(output)
      1303│ 
      1304│     def execute(self, bin: str, *args: str, **kwargs: Any) -> Optional[int]:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /root/.cache/pypoetry/artifacts/50/6f/ff/4ff20a62776b87b2ce071ac4039796d19cf95b3d467b9dfd00fa994b17/pytorch-1.0.2.tar.gz

  at /opt/poetry/venv/lib/python3.10/site-packages/poetry/utils/pip.py:60 in pip_install
       56│                     *env.get_pip_command(),
       57│                     *args,
       58│                     env={**os.environ, "PYTHONPATH": str(env.purelib)},
       59│                 )
    →  60│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       61│ 
       62│ 
       63│ def pip_editable_install(directory: Path, environment: Env) -> Union[int, str]:
       64│     return pip_install(
```

**Comment by tok41** [comment]
CPU版だと `poetry add torch` でインストールできた

**Comment by tok41** [comment]
とりあえずこれでcloseする（問題があれば再度作成）
